<head>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
</head>

<div class="container">
    <div class="row">
        <div class="col-md-6 offset-md-3">

            <?php if (count($flash) > 0) : ?>
                <ul>
                    <?php foreach ($flash as $messages) : ?>
                        <?php foreach ($messages as $message) : ?>
                            <div class="badge bg-primary text-wrap">
                                <a align="center"><?= $message ?></a>
                            </div>
                        <?php endforeach ?>
                    <?php endforeach ?>
                </ul>
            <?php endif ?>

            <h1>Authentification</h1>

            <form action="/session" method="post">
                <div class="form-group">
                    <label for="email"> Email</label>
                    <input type="text" class="form-control" required name="user[email]">
                </div>

                <div class="form-group">
                    <input type="submit" class="btn btn-primary mb-3" value="Sing in">
                </div>

            </form>
        </div>
    </div>
</div>