<head>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
</head>

<body>
    <div class="container">
        <div class="row">
            <div class="col-md-2 offset-md-3">
                <h1>Пользователи</h1>
                <form action="/users">
                    <input class="form-control" type="search" name="term" value="<?= htmlspecialchars($term) ?>">
                    <br><input class="btn btn-primary btn-sm" type="submit" value="Search">
                </form>

                <table class="table table-hover">
                    <thead>
                        <tr>
                            <th scope="col">id</th>
                            <th scope="col">Name</th>
                            <th scope="col">Email</th>
                        </tr>
                    </thead>
                    <?php foreach ($users as $user) : ?>
                        <tr>
                            <td class="table-light"><?= htmlspecialchars($user['id']) ?></td>
                            <td class="table-light"><?= htmlspecialchars($user['name']) ?></td>
                            <td class="table-light"><?= htmlspecialchars($user['email']) ?></td>
                        </tr>
                    <?php endforeach ?>
                </table>

                <form action="/users/new" method="get">
                    <br><br><button class="btn btn-outline-success">add user</button>
                </form>
            </div>
        </div>
    </div>
</body>